### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by kirtan0000** [benawad/vsinder#214]
When I try to login with GitHub, I get this message:
![image](https://user-images.githubusercontent.com/67987854/109208681-78f73f00-775f-11eb-8f3f-5b19c66fadea.png)

**Comment by QuantumlyTangled** [comment]
I have the same issue.
The URL starts with `http://localhost:54321/callback` and is continued with the random token.

**Comment by nimit2801** [comment]
I looked up into the codebase and found that [here](https://github.com/benawad/vsinder/blob/26464e3b83d76878a2df6ba28070b2023ea7663b/packages/api/src/index.ts) line 300 the redirect URL is still `http://localhost:54321/callback`. I guess this can be solved by adding the right callback URL there. I would love to open a PR.

Thoughts @unDeadHerbs  ?

**Comment by unDeadHerbs** [comment]
I don't know anything about typescript; but, looking at the contextual code, that seems to be the third fall though after trying/checking the more likely places.  That's probably there for development of debugging.  Rather than changing the URL, I'd check what those `if`s are on and why they are falling through.

**Comment by kirtan0000** [comment]
This issue is fixed and I will now close it

**Comment by AshutoshSajan** [comment]
facing the same issue
